spring:
    application:
        name: be
    profiles:
        active: local
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: ${DB_USERNAME}
        url: ${DB_URL}
        password: ${DB_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: 'true'
    security:
      oauth2:
        client:
          registration:
            github:
              clientId: ${GITHUB_CLIENT_ID}
              clientSecret: ${GITHUB_CLIENT_SECRET}
              scope:
                - user
                - project
                - repo
    neo4j:
      uri: bolt://localhost:7687
      authentication:
        username: ${NEO4J_USERNAME}
        password: ${NEO4J_PASSWORD}
    data:
      neo4j:
        database: neo4j
